select * from SYS.DBA_ROLES;
grant execute on VYDRA_DBA.ACCOUNT_HISTORY to CLIENT_ROlE;
grant execute on VYDRA_DBA.ACCOUNT_TURNOVER to CLIENT_ROlE;
grant execute on VYDRA_DBA.ACCOUNTS_AMOUNT to CLIENT_ROlE;
grant execute on VYDRA_DBA.CLIENT_INFO_CHANGING to CLIENT_ROlE;
grant execute on VYDRA_DBA.COUNT_DEPOSIT_PROFIT to CLIENT_ROlE;
grant execute on VYDRA_DBA.GET_USER_INFO to CLIENT_ROlE;
grant execute on VYDRA_DBA.LOGIN_CLIENT to CLIENT_ROlE;
grant execute on VYDRA_DBA.OPERATIONS_AMOUNT to CLIENT_ROlE;
grant execute on VYDRA_DBA.REFILL_ACCOUNT to CLIENT_ROlE;
grant execute on VYDRA_DBA.REGISTER_CLIENT to CLIENT_ROlE;
grant execute on VYDRA_DBA.TRANSFER to CLIENT_ROlE;
grant execute on VYDRA_DBA.WITHDRAWAL to CLIENT_ROlE;



grant execute on VYDRA_DBA.CHANGE_CLIENT_ACCOUNT_TYPE to CLERK_ROLE;
grant execute on VYDRA_DBA.CLERK_LOGIN to CLERK_ROLE;
grant execute on VYDRA_DBA.CLIENT_CREATION to CLERK_ROLE;
grant execute on VYDRA_DBA.CLIENT_DELETE to CLERK_ROLE;
grant execute on VYDRA_DBA.CREATE_ACCOUNT_FOR_CLIENT to CLERK_ROLE;
grant execute on VYDRA_DBA.CREATE_DEPOSIT to CLERK_ROLE;
grant execute on VYDRA_DBA.CREATE_DEPOSIT_CONDITION to CLERK_ROLE;
grant execute on VYDRA_DBA.DELETE_ACCOUNT_FOR_CLIENT to CLERK_ROLE;
grant execute on VYDRA_DBA.DELETE_DEPOSIT_CONDITION to CLERK_ROLE;

GRANT DEBUG CONNECT SESSION TO CLIENT1;
GRANT DEBUG CONNECT SESSION TO CLERK1;

select * from dba_users;