-- USER SQL
ALTER USER "VYDRA_DBA"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;
grant "DBA","PPLB_ROLE","DV_MONITOR","CTXAPP","DV_AUDIT_CLEANUP","EM_EXPRESS_ALL","OLAP_XS_ADMIN","DV_SECANALYST","MAINTPLAN_APP","RECOVERY_CATALOG_OWNER_VPD","XS_CACHE_ADMIN","AVTUNE_PKG_ROLE","GDS_CATALOG_SELECT","SCHEDULER_ADMIN","PROVISIONER","AUDIT_ADMIN","XDB_WEBSERVICES_OVER_HTTP","AQ_ADMINISTRATOR_ROLE","SYSUMF_ROLE","APPLICATION_TRACE_VIEWER","XDB_WEBSERVICES","LBAC_DBA","OPTIMIZER_PROCESSING_RATE","RECOVERY_CATALOG_USER","DV_DATAPUMP_NETWORK_LINK","GSMUSER_ROLE","GATHER_SYSTEM_STATISTICS","LOGSTDBY_ADMINISTRATOR","GSM_POOLADMIN_ROLE","DV_ADMIN","DV_POLICY_OWNER","HS_ADMIN_ROLE","XS_SESSION_ADMIN","DV_GOLDENGATE_ADMIN","IMP_FULL_DATABASE","DV_XSTREAM_ADMIN","DV_PATCH_ADMIN","GGSYS_ROLE","DATAPUMP_EXP_FULL_DATABASE","HS_ADMIN_EXECUTE_ROLE","ADM_PARALLEL_EXECUTE_TASK","SELECT_CATALOG_ROLE","CONNECT","ACCHK_READ","DATAPUMP_IMP_FULL_DATABASE","SODA_APP","BDSQL_ADMIN","OEM_MONITOR","GSMADMIN_ROLE","AQ_USER_ROLE","XDB_SET_INVOKER","RECOVERY_CATALOG_OWNER","DBFS_ROLE","PDB_DBA","RDFCTX_ADMIN","DV_GOLDENGATE_REDO_ACCESS","CDB_DBA","GSMROOTUSER_ROLE","HS_ADMIN_SELECT_ROLE","AUDIT_VIEWER","RESOURCE","DV_OWNER","XDB_WEBSERVICES_WITH_PUBLIC","EXECUTE_CATALOG_ROLE","DATAPATCH_ROLE","DV_ACCTMGR","EXP_FULL_DATABASE","DBMS_MDX_INTERNAL","DV_STREAMS_ADMIN","XS_NAMESPACE_ADMIN","BDSQL_USER","AUTHENTICATEDUSER","CAPTURE_ADMIN","OEM_ADVISOR","XS_CONNECT","XDBADMIN","EM_EXPRESS_BASIC" to VYDRA_DBA;

-- SYSTEM PRIVILEGES

grant all privileges to VYDRA_DBA;
grant create session to VYDRA_DBA;



-- Создайте динамический SQL для предоставления всех ролей пользователю
DECLARE
  v_sql VARCHAR2(1000);
BEGIN
  FOR role_rec IN (SELECT role FROM dba_roles) LOOP
    v_sql := 'GRANT ' || role_rec.role || ' TO VYDRA_DBA';
    EXECUTE IMMEDIATE v_sql;
  END LOOP;
END;
/





GRANT DBA TO VYDRA_DBA;
GRANT CONNECT TO VYDRA_DBA;
GRANT CREATE TABLE TO VYDRA_DBA;
GRANT CREATE SEQUENCE TO VYDRA_DBA;
GRANT CREATE VIEW TO VYDRA_DBA;
GRANT CREATE INDEXTYPE TO VYDRA_DBA;
GRANT CREATE PROFILE TO VYDRA_DBA;
GRANT CREATE PROCEDURE TO VYDRA_DBA;
GRANT CREATE TRIGGER TO VYDRA_DBA;
GRANT CREATE SESSION TO VYDRA_DBA;
GRANT CREATE ROLE TO VYDRA_DBA;
GRANT CREATE JOB TO VYDRA_DBA;
GRANT EXECUTE ON DBMS_CRYPTO TO VYDRA_DBA;





-- Connect to the Oracle Database as a user with DBA privileges
CONNECT sys AS sysdba;

-- Grant roles and privileges to vydra_dba
GRANT ACCHK_READ TO vydra_dba;
GRANT ADM_PARALLEL_EXECUTE_TASK TO vydra_dba;
GRANT APPLICATION_TRACE_VIEWER TO vydra_dba;
GRANT AQ_ADMINISTRATOR_ROLE TO vydra_dba;
GRANT AQ_USER_ROLE TO vydra_dba;
-- Add other roles and privileges here
GRANT XS_CONNECT TO vydra_dba;
GRANT XS_NAMESPACE_ADMIN TO vydra_dba;
GRANT XS_SESSION_ADMIN TO vydra_dba;

-- Create other roles and privileges if needed
-- CREATE ROLE your_role;
-- GRANT your_role TO vydra_dba;
-- GRANT your_privilege TO vydra_dba;

-- Exit the session